[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]
solc = "0.8.27"
via-ir = true

remappings = [
    "@eigenlayer/=lib/eigenlayer-middleware/lib/eigenlayer-contracts/src/",
    "@eigenlayer-scripts/=lib/eigenlayer-middleware/lib/eigenlayer-contracts/script/",
    "@eigenlayer-middleware/=lib/eigenlayer-middleware/",
    "@openzeppelin/=lib/eigenlayer-middleware/lib/openzeppelin-contracts/",
    "@openzeppelin-upgrades/=lib/eigenlayer-middleware/lib/openzeppelin-contracts-upgradeable/",
    "forge-std/=lib/forge-std/src/",
]

# Additional compiler profiles
additional_compiler_profiles = [
    { name = "optimized", optimizer = true, optimizer_runs = 200 }
]

# Compilation restrictions
compilation_restrictions = [
    { paths = "script/IncredibleSquaringDeployer.s.sol", profile = "optimized" }
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
